package com.gkiss01.meetdebwebapi.utils;

import lombok.Getter;

@Getter
public enum ErrorCodes {
    USER_DISABLED_OR_NOT_VALID(10),
    ACCESS_DENIED(11),
    BAD_REQUEST_FORMAT(12),
    UNKNOWN(13),

    USER_NOT_FOUND(100),
    NO_USERS_FOUND(101),
    CONFIRMATION_TOKEN_NOT_FOUND(102),
    USER_ALREADY_VERIFIED(103),
    EMAIL_ALREADY_IN_USE(104),

    EVENT_NOT_FOUND(200),
    NO_EVENTS_FOUND(201),

    PARTICIPANT_NOT_FOUND(300),
    NO_PARTICIPANTS_FOUND(301),
    PARTICIPANT_ALREADY_CREATED(304),

    DATE_NOT_FOUND(400),
    NO_DATES_FOUND(401),
    DATE_ALREADY_CREATED(404),

    VOTE_NOT_FOUND(500),
    VOTE_ALREADY_CREATED(504),

    FILE_NOT_FOUND(600),
    FILENAME_INVALID(601),
    COULD_NOT_CONVERT_IMAGE(602),
    FILE_SIZE_LIMIT_EXCEEDED(603),
    UPLOAD_FAILED(604),
    COULD_NOT_CREATE_DIRECTORY(605);

    private final int code;

    ErrorCodes(int code) {
        this.code = code;
    }
}